# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  application.yml: |  # 注意缩进格式
    spring:
      application:
        name: configMap--backend-service-2
    server:
      port: 9000
